<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Figures/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Maestría en Ciencia de Datos</h1>
        <h3 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Ingeniería de Características</h3>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 1: Extracción de datos de diferentes fuentes</h3>
    </div>
</div>


## Propósito

La extracción es el primer paso para convertir información heterogénea en datos analizables. En este cuaderno se practican técnicas para leer archivos tabulares, texto libre, documentos jerárquicos, datos geoespaciales, páginas web e imágenes.

### Resultados de aprendizaje

- elegir una estrategia de lectura según la estructura de la fuente;
- inspeccionar tipos, dimensiones, columnas y valores antes de analizar;
- transformar datos anidados o no estructurados en tablas;
- identificar riesgos de calidad, codificación, rutas y reproducibilidad.

> **Idea central:** extraer datos no significa únicamente abrir un archivo. Significa conservar su significado, documentar los supuestos y producir una representación útil para la siguiente etapa del flujo de ciencia de datos.

```mermaid
flowchart LR
    A[Fuente original] --> B[Lectura]
    B --> C[Inspección]
    C --> D[Limpieza y transformación]
    D --> E[DataFrame o matriz]
    E --> F[Análisis y modelado]
```

## 1. Preparar el entorno y las rutas

Antes de leer una fuente conviene centralizar la carpeta de datos. Así se evita repetir rutas, se facilita mover el cuaderno y se hace más clara la procedencia de cada archivo.

En un proyecto reproducible, la ruta debe ser relativa al proyecto o construirse con `pathlib`. En los ejemplos siguientes se conserva la variable `ruta` para trabajar con los archivos didácticos del curso.

In [1]:
# Almacenamos la ruta de los archivos en una variable
ruta='Data/'

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Maestría Ciencia de Datos\\Ingeniería de Características\\Ingenieria_Caracteristicas_O2026\\Módulo 1 - Extracción de datos de diferentes fuentes'

In [4]:
os.listdir(ruta)

['API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls',
 'conteo_palabras.csv',
 'data.json',
 'df_tabla2.csv',
 'ejemplo.html',
 'Extracción.ipynb',
 'IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml',
 'imagen.bmp',
 'tabla_1.xml',
 'tabla_2.xml',
 'texto_1.txt',
 'texto_2.txt',
 'texto_3.txt']

In [8]:
ruta_csv = os.path.join(os.getcwd(), 'Data', 'df_tabla1.csv')
ruta_csv

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Maestría Ciencia de Datos\\Ingeniería de Características\\Ingenieria_Caracteristicas_O2026\\Módulo 1 - Extracción de datos de diferentes fuentes\\Data\\df_tabla1.csv'

In [9]:
os.path.exists(ruta_csv)

False

In [11]:
try:
    ruta_csv = os.path.join(os.getcwd(), 'Data', 'df_tabla1.csv')
    df = pd.read_csv(ruta_csv)
except:
    print('No se encontró el archivo')
    None

No se encontró el archivo

In [12]:
if os.path.exists(ruta_csv):
    df = pd.read_csv(ruta_csv)
else:
    print('No se encontró el archivo')

No se encontró el archivo

In [13]:
os.path.dirname(ruta_csv)

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Maestría Ciencia de Datos\\Ingeniería de Características\\Ingenieria_Caracteristicas_O2026\\Módulo 1 - Extracción de datos de diferentes fuentes\\Data'

In [14]:
os.path.basename(ruta_csv)

'df_tabla1.csv'

In [16]:
os.path.splitext(os.path.basename(ruta_csv))

('df_tabla1', '.csv')

In [18]:
archivos_texto = [f for f in os.listdir(ruta) if f.endswith('.txt')]

In [19]:
ruta

'Data/'

In [20]:
for nombre in archivos_texto:
    ruta_completa = os.path.join(ruta, nombre)
    print(f'{nombre}: {os.path.getsize(ruta_completa)} bytes')

texto_1.txt: 55 bytes
texto_2.txt: 68 bytes
texto_3.txt: 1226 bytes

In [ ]:
def get_data_and_sizes(ruta_base, data_type):

    return

In [21]:
#os.walk
for carpeta_actual, subcarpetas, archivos in os.walk(ruta):
    print('Carpeta: ', carpeta_actual)
    print('Subcarpetas: ', subcarpetas)
    print('Archivos: ', archivos)

Carpeta:  Data/
Subcarpetas:  []
Archivos:  ['API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls', 'conteo_palabras.csv', 'data.json', 'df_tabla2.csv', 'ejemplo.html', 'Extracción.ipynb', 'IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml', 'imagen.bmp', 'tabla_1.xml', 'tabla_2.xml', 'texto_1.txt', 'texto_2.txt', 'texto_3.txt']

# 2. Archivos Excel y CSV

Los archivos CSV y Excel representan datos tabulares: cada fila suele corresponder a una observación y cada columna a una variable. Son frecuentes en reportes, exportaciones de sistemas y conjuntos de datos pequeños o medianos.

`pandas` permite cargarlos en un `DataFrame`, una estructura que facilita filtrar, resumir y transformar datos. La lectura correcta depende de detalles como el separador, la codificación, los encabezados y los valores faltantes.

**Checklist de inspección:** después de cargar un archivo revisa `shape`, `columns`, `dtypes`, valores nulos y algunas filas. En el ejemplo se elimina `Unnamed: 0`, una columna índice que suele aparecer cuando un DataFrame se exportó sin `index=False`.

In [22]:
import pandas as pd

In [23]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0


In [24]:
df_csv = pd.read_csv(ruta+'df_tabla2.csv')
print('Contenido del archivo CSV:')
print(df_csv)

Contenido del archivo CSV:
   Unnamed: 0        country  rank  year   gdppc
0           0  Liechtenstein     1  2008  141100
1           1      Singapore     4  2011   59900
2           2         Panama    68  2011   13600

In [25]:
df_csv

   Unnamed: 0        country  rank  year   gdppc
0           0  Liechtenstein     1  2008  141100
1           1      Singapore     4  2011   59900
2           2         Panama    68  2011   13600

In [26]:
df_csv

   Unnamed: 0        country  rank  year   gdppc
0           0  Liechtenstein     1  2008  141100
1           1      Singapore     4  2011   59900
2           2         Panama    68  2011   13600

In [27]:
df_csv.iloc[:,0]

0    0
1    1
2    2
Name: Unnamed: 0, dtype: int64

In [28]:
df_csv = df_csv.drop('Unnamed: 0', axis=1)
df_csv

         country  rank  year   gdppc
0  Liechtenstein     1  2008  141100
1      Singapore     4  2011   59900
2         Panama    68  2011   13600

In [32]:
df2 = pd.read_csv(ruta+'df_tabla2.csv', index_col=[0])
df2

         country  rank  year   gdppc
0  Liechtenstein     1  2008  141100
1      Singapore     4  2011   59900
2         Panama    68  2011   13600

In [ ]:
df2

In [34]:
pd.read_csv(ruta+'df_tabla2.csv', index_col=[3]).drop('Unnamed: 0', axis=1)

            country  rank   gdppc
year
2008  Liechtenstein     1  141100
2011      Singapore     4   59900
2011         Panama    68   13600

In [35]:
df2

         country  rank  year   gdppc
0  Liechtenstein     1  2008  141100
1      Singapore     4  2011   59900
2         Panama    68  2011   13600

In [36]:
df2.set_index('year')

            country  rank   gdppc
year
2008  Liechtenstein     1  141100
2011      Singapore     4   59900
2011         Panama    68   13600

In [38]:
df2.set_index('year', inplace = True)

In [39]:
df2

            country  rank   gdppc
year
2008  Liechtenstein     1  141100
2011      Singapore     4   59900
2011         Panama    68   13600

In [41]:
df2.iloc[0,1]

np.int64(1)

In [43]:
df2.loc[2008, 'country']

'Liechtenstein'

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 2008 to 2011
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  3 non-null      object
 1   rank     3 non-null      int64
 2   gdppc    3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [47]:
df2.shape

(3, 3)

# 3. Archivos de texto

Los archivos de texto no siempre tienen una estructura explícita. Para extraerlos hay que determinar si sus campos están separados por tabuladores, comas, espacios u otro delimitador, o si cada columna ocupa un ancho fijo.

### De texto a `DataFrame`

La estrategia elegida debe corresponder al formato real. Si el separador cambia entre filas, hay que normalizar la fuente antes de convertirla en tabla; si el archivo contiene texto libre, conviene leerlo como una cadena y aplicar técnicas de procesamiento de lenguaje.

`pd.read_fwf` de pandas se utiliza para leer archivos de texto con columnas de ancho fijo (*fixed-width formatted lines*) y cargarlos en un DataFrame. En este formato, la posición de los caracteres define cada columna, no un separador visible.

Es útil para reportes heredados o archivos generados por sistemas antiguos. Antes de usarlo, confirma que las posiciones de inicio y fin sean consistentes en varias filas.

In [48]:
# Extracción a partir de texto separado por tabular
pd.read_fwf(ruta+'texto_2.txt',header=None) # No se puede especificar el separador

         0    1   2
0      Ana  1.0  10
1     Beto  1.1  10
2  Alfredo  6.0   9
3  Armando  5.0   9

`read_table` de pandas se utiliza para leer archivos de texto delimitados (por defecto, separados por tabulaciones) y cargarlos en un DataFrame

In [50]:
print('\t')

In [51]:
pd.read_table(ruta+'texto_2.txt',header=None) # sep='\t'

          0    1   2
0  Ana       1.0  10
1  Beto      1.1  10
2  Alfredo   6.0   9
3  Armando   5.0   9

In [52]:
# Extracción a partir de texto separado por comas
pd.read_table(ruta+'texto_1.txt',sep=',',header=None)

         0    1   2
0      Ana  1.0  10
1     Beto  1.1  10
2  Alfredo  6.0   9
3  Armando  5.0   9

In [53]:
pd.read_table(ruta+'texto_1.txt',sep=' ',header=None)

          0     1   2
0      Ana,    1,  10
1     Beto,  1.1,  10
2  Alfredo,    6,   9
3  Armando,    5,   9

In [54]:
pd.read_csv(ruta+'texto_2.txt',header=None,sep='\t') # sep=','

          0    1   2
0  Ana       1.0  10
1  Beto      1.1  10
2  Alfredo   6.0   9
3  Armando   5.0   9

In [55]:
# Conversión de archivo a variable
file=open(ruta+'texto_3.txt')     # Abrir...
texto=file.read()
file.close()                      # ...despues cerrar

In [56]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [57]:
# Si ocurre un error durante la ejecución, la variable file se cierra siempre:
with open(ruta+'texto_3.txt') as file:
  texto=file.read()

In [58]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [59]:
# Separamos cada palabra de la variable de texto
texto.split()

['En',
 'un',
 'lugar',
 'de',
 'la',
 'Mancha,',
 'de',
 'cuyo',
 'nombre',
 'no',
 'quiero',
 'acordarme,',
 'no',
 'ha',
 'mucho',
 'tiempo',
 'que',
 'vivÃ\xada',
 'un',
 'hidalgo',
 'de',
 'los',
 'de',
 'lanza',
 'en',
 'astillero,',
 'adarga',
 'antigua,',
 'rocÃ³n',
 'flaco',
 'y',
 'galgo',
 'corredor.',
 'Una',
 'olla',
 'de',
 'algo',
 'mÃ¡s',
 'vaca',
 'que',
 'carnero,',
 'salpicÃ³n',
 'las',
 'mÃ¡s',
 'noches,',
 'duelos',
 'y',
 'quebrantos',
 'los',
 'sÃ¡bados,',
 'lantejas',
 'los',
 'viernes,',
 'algÃºn',
 'palomino',
 'de',
 'aÃ±adidura',
 'los',
 'domingos,',
 'consumÃ\xadan',
 'las',
 'tres',
 'partes',
 'de',
 'su',
 'hacienda.',
 'El',
 'resto',
 'della',
 'concluÃ\xadan',
 'sayo',
 'de',
 'velarte,',
 'calzas',
 'de',
 'velludo',
 'para',
 'las',
 'fiestas,',
 'con',
 'sus',
 'pantuflos',
 'de',
 'lo',
 'mesmo,',
 'y',
 'los',
 'dÃ\xadas',
 'de',
 'entresemana',
 'se',
 'honraba',
 'con',
 'su',
 'vellorÃ\xad',
 'de',
 'lo',
 'mÃ¡s',
 'fino.',
 'TenÃ\xada',
 'en',
 'su',
 'casa',
 'una',
 'ama',
 'que',
 'pasaba',
 'de',
 'los',
 'cuarenta,',
 'y',
 'una',
 'sobrina',
 'que',
 'no',
 'llegaba',
 'a',
 'los',
 'veinte,',
 'y',
 'un',
 'mozo',
 'de',
 'campo',
 'y',
 'plaza,',
 'que',
 'asÃ\xad',
 'ensillaba',
 'el',
 'rocÃ\xadn',
 'como',
 'tomaba',
 'la',
 'podadera.',
 'Frisaba',
 'la',
 'edad',
 'de',
 'nuestro',
 'hidalgo',
 'con',
 'los',
 'cincuenta',
 'aÃ±os;',
 'era',
 'de',
 'complexiÃ³n',
 'recia,',
 'seco',
 'de',
 'carnes,',
 'enjuto',
 'de',
 'rostro,',
 'gran',
 'madrugador',
 'y',
 'amigo',
 'de',
 'la',
 'caza.',
 'Quieren',
 'decir',
 'que',
 'tenÃ\xada',
 'el',
 'sobrenombre',
 'de',
 'Quijada,',
 'o',
 'Quesada,',
 'que',
 'en',
 'esto',
 'hay',
 'alguna',
 'diferencia',
 'en',
 'los',
 'autores',
 'que',
 'deste',
 'caso',
 'escriben;',
 'aunque',
 'por',
 'conjeturas',
 'verosÃ\xadmiles',
 'se',
 'deja',
 'entender',
 'que',
 'se',
 'llamaba',
 'Quijana.',
 'Pero',
 'esto',
 'importa',
 'poco',
 'a',
 'nuestro',
 'cuento:',
 'basta',
 'que',
 'en',
 'la',
 'narraciÃ³n',
 'dÃ©l',
 'no',
 'se',
 'salga',
 'un',
 'punto',
 'de',
 'la',
 'verdad.']

In [60]:
texto.split?

Signature: texto.split(sep=None, maxsplit=-1)
Docstring:
Return a list of the substrings in the string, using sep as the separator string.

  sep
    The separator used to split the string.

    When set to None (the default value), will split on any whitespace
    character (including \\n \\r \\t \\f and spaces) and will discard
    empty strings from the result.
  maxsplit
    Maximum number of splits (starting from the left).
    -1 (the default value) means no limit.

Note, str.split() is mainly useful for data that has been intentionally
delimited.  With natural text that includes punctuation, consider using
the regular expression module.
Type:      builtin_function_or_method

In [61]:
with open(ruta+'texto_3.txt', encoding='utf-8') as file:
  texto=file.read()

In [62]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocón flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosímiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narración dél no se salga un punto de la verdad.'

In [68]:
#Natural Lenguage Processing (BOW)
texto.lower().split()

['en',
 'un',
 'lugar',
 'de',
 'la',
 'mancha,',
 'de',
 'cuyo',
 'nombre',
 'no',
 'quiero',
 'acordarme,',
 'no',
 'ha',
 'mucho',
 'tiempo',
 'que',
 'vivía',
 'un',
 'hidalgo',
 'de',
 'los',
 'de',
 'lanza',
 'en',
 'astillero,',
 'adarga',
 'antigua,',
 'rocón',
 'flaco',
 'y',
 'galgo',
 'corredor.',
 'una',
 'olla',
 'de',
 'algo',
 'más',
 'vaca',
 'que',
 'carnero,',
 'salpicón',
 'las',
 'más',
 'noches,',
 'duelos',
 'y',
 'quebrantos',
 'los',
 'sábados,',
 'lantejas',
 'los',
 'viernes,',
 'algún',
 'palomino',
 'de',
 'añadidura',
 'los',
 'domingos,',
 'consumían',
 'las',
 'tres',
 'partes',
 'de',
 'su',
 'hacienda.',
 'el',
 'resto',
 'della',
 'concluían',
 'sayo',
 'de',
 'velarte,',
 'calzas',
 'de',
 'velludo',
 'para',
 'las',
 'fiestas,',
 'con',
 'sus',
 'pantuflos',
 'de',
 'lo',
 'mesmo,',
 'y',
 'los',
 'días',
 'de',
 'entresemana',
 'se',
 'honraba',
 'con',
 'su',
 'vellorí',
 'de',
 'lo',
 'más',
 'fino.',
 'tenía',
 'en',
 'su',
 'casa',
 'una',
 'ama',
 'que',
 'pasaba',
 'de',
 'los',
 'cuarenta,',
 'y',
 'una',
 'sobrina',
 'que',
 'no',
 'llegaba',
 'a',
 'los',
 'veinte,',
 'y',
 'un',
 'mozo',
 'de',
 'campo',
 'y',
 'plaza,',
 'que',
 'así',
 'ensillaba',
 'el',
 'rocín',
 'como',
 'tomaba',
 'la',
 'podadera.',
 'frisaba',
 'la',
 'edad',
 'de',
 'nuestro',
 'hidalgo',
 'con',
 'los',
 'cincuenta',
 'años;',
 'era',
 'de',
 'complexión',
 'recia,',
 'seco',
 'de',
 'carnes,',
 'enjuto',
 'de',
 'rostro,',
 'gran',
 'madrugador',
 'y',
 'amigo',
 'de',
 'la',
 'caza.',
 'quieren',
 'decir',
 'que',
 'tenía',
 'el',
 'sobrenombre',
 'de',
 'quijada,',
 'o',
 'quesada,',
 'que',
 'en',
 'esto',
 'hay',
 'alguna',
 'diferencia',
 'en',
 'los',
 'autores',
 'que',
 'deste',
 'caso',
 'escriben;',
 'aunque',
 'por',
 'conjeturas',
 'verosímiles',
 'se',
 'deja',
 'entender',
 'que',
 'se',
 'llamaba',
 'quijana.',
 'pero',
 'esto',
 'importa',
 'poco',
 'a',
 'nuestro',
 'cuento:',
 'basta',
 'que',
 'en',
 'la',
 'narración',
 'dél',
 'no',
 'se',
 'salga',
 'un',
 'punto',
 'de',
 'la',
 'verdad.']

In [70]:
voc = set(texto.lower().split())
voc

{'a',
 'acordarme,',
 'adarga',
 'algo',
 'alguna',
 'algún',
 'ama',
 'amigo',
 'antigua,',
 'astillero,',
 'así',
 'aunque',
 'autores',
 'añadidura',
 'años;',
 'basta',
 'calzas',
 'campo',
 'carnero,',
 'carnes,',
 'casa',
 'caso',
 'caza.',
 'cincuenta',
 'como',
 'complexión',
 'con',
 'concluían',
 'conjeturas',
 'consumían',
 'corredor.',
 'cuarenta,',
 'cuento:',
 'cuyo',
 'de',
 'decir',
 'deja',
 'della',
 'deste',
 'diferencia',
 'domingos,',
 'duelos',
 'dél',
 'días',
 'edad',
 'el',
 'en',
 'enjuto',
 'ensillaba',
 'entender',
 'entresemana',
 'era',
 'escriben;',
 'esto',
 'fiestas,',
 'fino.',
 'flaco',
 'frisaba',
 'galgo',
 'gran',
 'ha',
 'hacienda.',
 'hay',
 'hidalgo',
 'honraba',
 'importa',
 'la',
 'lantejas',
 'lanza',
 'las',
 'llamaba',
 'llegaba',
 'lo',
 'los',
 'lugar',
 'madrugador',
 'mancha,',
 'mesmo,',
 'mozo',
 'mucho',
 'más',
 'narración',
 'no',
 'noches,',
 'nombre',
 'nuestro',
 'o',
 'olla',
 'palomino',
 'pantuflos',
 'para',
 'partes',
 'pasaba',
 'pero',
 'plaza,',
 'poco',
 'podadera.',
 'por',
 'punto',
 'que',
 'quebrantos',
 'quesada,',
 'quieren',
 'quiero',
 'quijada,',
 'quijana.',
 'recia,',
 'resto',
 'rocín',
 'rocón',
 'rostro,',
 'salga',
 'salpicón',
 'sayo',
 'se',
 'seco',
 'sobrenombre',
 'sobrina',
 'su',
 'sus',
 'sábados,',
 'tenía',
 'tiempo',
 'tomaba',
 'tres',
 'un',
 'una',
 'vaca',
 'veinte,',
 'velarte,',
 'vellorí',
 'velludo',
 'verdad.',
 'verosímiles',
 'viernes,',
 'vivía',
 'y'}

In [71]:
len(voc)

137

### 3.1 Expresiones regulares

Las **expresiones regulares** (*regex*) describen patrones de texto. Son apropiadas cuando la fuente no tiene una estructura tabular, pero sí reglas repetibles: correos, fechas, identificadores o códigos.

El flujo habitual es: definir el patrón, probarlo con ejemplos representativos, extraer coincidencias y validar los casos que no coincidan. Una regex demasiado general puede capturar datos incorrectos; una demasiado estricta puede omitir variaciones válidas.

Las **expresiones regulares** (regex) son patrones que se utilizan para buscar, extraer o manipular texto de manera flexible y eficiente. Permiten identificar cadenas de texto que cumplen ciertas reglas, como correos electrónicos, números de teléfono, palabras específicas, etc.

##### ¿Cómo se usan en Python?

En Python, se utiliza el módulo `re` para trabajar con expresiones regulares. Algunas funciones comunes son:

- `re.search()`: busca un patrón en cualquier posición y devuelve la primera coincidencia.
- `re.match()`: comprueba la coincidencia desde el inicio de la cadena.
- `re.findall()`: devuelve todas las coincidencias como una lista.
- `re.split()`: divide el texto usando el patrón como separador.
- `re.sub()`: reemplaza coincidencias por otro texto.

##### ¿Cómo definir patrones en regex?

- Los patrones se definen como cadenas de texto; el prefijo `r` evita que Python interprete algunas barras invertidas antes que regex.
- Algunos caracteres especiales:
  - `.`: cualquier carácter excepto salto de línea
  - `\d`: un dígito (0-9)
  - `\w`: un carácter alfanumérico o guion bajo
  - `\s`: un espacio en blanco
  - `*`: cero o más repeticiones
  - `+`: una o más repeticiones
  - `?`: cero o una repetición
  - `^`: inicio de línea
  - `$`: fin de línea
  - `[abc]`: cualquier carácter a, b o c
  - `( )`: agrupación y captura

> **Lectura del ejemplo:** `\w+@\w+\.\w+` busca una estructura simple de correo. Es útil para aprender, pero no pretende validar todas las direcciones permitidas por los estándares de correo.

###### Ejemplo: Correos electrónicos

In [72]:
import re

texto_correo = "Mi correo es gdesirena@iteso.mx pero anteriormente usaba gdesirena@gmail.com"
patron = r"\w+@\w+\.\w+"  # patrón para un correo electrónico

resultado = re.search(patron, texto_correo)
if resultado:
    print("Correo encontrado:", resultado.group())

Correo encontrado: gdesirena@iteso.mx

In [73]:
correos = re.findall(patron, texto_correo) #Encuentra todos los correos en texto_correo
correos

['gdesirena@iteso.mx', 'gdesirena@gmail.com']

In [74]:
df_correos = pd.DataFrame({'correo': correos})
df_correos

                correo
0   gdesirena@iteso.mx
1  gdesirena@gmail.com

In [75]:
dominios = re.findall(r'@([\w\.-]+)', texto_correo) #captura el dominio después del @
print('Dominios encontrados:', dominios)

Dominios encontrados: ['iteso.mx', 'gmail.com']

In [76]:
texto_fechas = 'algunas fechas importantes son 15/09/2023 y 01/01/2024.' 
fechas = re.findall(r'\b\d{2}/\d{2}/\d{4}\b', texto_fechas) #Encuentra todas las fechas
print('Fechas encontradas:', fechas)

Fechas encontradas: ['15/09/2023', '01/01/2024']

###### Ejemplo: Conteo de palabras usando regex

In [ ]:
#re.split?

In [77]:
L=re.split(r'\W',texto)
L

['En',
 'un',
 'lugar',
 'de',
 'la',
 'Mancha',
 '',
 'de',
 'cuyo',
 'nombre',
 'no',
 'quiero',
 'acordarme',
 '',
 'no',
 'ha',
 'mucho',
 'tiempo',
 'que',
 'vivía',
 'un',
 'hidalgo',
 'de',
 'los',
 'de',
 'lanza',
 'en',
 'astillero',
 '',
 'adarga',
 'antigua',
 '',
 'rocón',
 'flaco',
 'y',
 'galgo',
 'corredor',
 '',
 'Una',
 'olla',
 'de',
 'algo',
 'más',
 'vaca',
 'que',
 'carnero',
 '',
 'salpicón',
 'las',
 'más',
 'noches',
 '',
 'duelos',
 'y',
 'quebrantos',
 'los',
 'sábados',
 '',
 'lantejas',
 'los',
 'viernes',
 '',
 'algún',
 'palomino',
 'de',
 'añadidura',
 'los',
 'domingos',
 '',
 'consumían',
 'las',
 'tres',
 'partes',
 'de',
 'su',
 'hacienda',
 '',
 'El',
 'resto',
 'della',
 'concluían',
 'sayo',
 'de',
 'velarte',
 '',
 'calzas',
 'de',
 'velludo',
 'para',
 'las',
 'fiestas',
 '',
 'con',
 'sus',
 'pantuflos',
 'de',
 'lo',
 'mesmo',
 '',
 'y',
 'los',
 'días',
 'de',
 'entresemana',
 'se',
 'honraba',
 'con',
 'su',
 'vellorí',
 'de',
 'lo',
 'más',
 'fino',
 '',
 'Tenía',
 'en',
 'su',
 'casa',
 'una',
 'ama',
 'que',
 'pasaba',
 'de',
 'los',
 'cuarenta',
 '',
 'y',
 'una',
 'sobrina',
 'que',
 'no',
 'llegaba',
 'a',
 'los',
 'veinte',
 '',
 'y',
 'un',
 'mozo',
 'de',
 'campo',
 'y',
 'plaza',
 '',
 'que',
 'así',
 'ensillaba',
 'el',
 'rocín',
 'como',
 'tomaba',
 'la',
 'podadera',
 '',
 'Frisaba',
 'la',
 'edad',
 'de',
 'nuestro',
 'hidalgo',
 'con',
 'los',
 'cincuenta',
 'años',
 '',
 'era',
 'de',
 'complexión',
 'recia',
 '',
 'seco',
 'de',
 'carnes',
 '',
 'enjuto',
 'de',
 'rostro',
 '',
 'gran',
 'madrugador',
 'y',
 'amigo',
 'de',
 'la',
 'caza',
 '',
 'Quieren',
 'decir',
 'que',
 'tenía',
 'el',
 'sobrenombre',
 'de',
 'Quijada',
 '',
 'o',
 'Quesada',
 '',
 'que',
 'en',
 'esto',
 'hay',
 'alguna',
 'diferencia',
 'en',
 'los',
 'autores',
 'que',
 'deste',
 'caso',
 'escriben',
 '',
 'aunque',
 'por',
 'conjeturas',
 'verosímiles',
 'se',
 'deja',
 'entender',
 'que',
 'se',
 'llamaba',
 'Quijana',
 '',
 'Pero',
 'esto',
 'importa',
 'poco',
 'a',
 'nuestro',
 'cuento',
 '',
 'basta',
 'que',
 'en',
 'la',
 'narración',
 'dél',
 'no',
 'se',
 'salga',
 'un',
 'punto',
 'de',
 'la',
 'verdad',
 '']

In [78]:
# Convertimos la lista a set
S=set(L)
S.discard('')
S

{'El',
 'En',
 'Frisaba',
 'Mancha',
 'Pero',
 'Quesada',
 'Quieren',
 'Quijada',
 'Quijana',
 'Tenía',
 'Una',
 'a',
 'acordarme',
 'adarga',
 'algo',
 'alguna',
 'algún',
 'ama',
 'amigo',
 'antigua',
 'astillero',
 'así',
 'aunque',
 'autores',
 'añadidura',
 'años',
 'basta',
 'calzas',
 'campo',
 'carnero',
 'carnes',
 'casa',
 'caso',
 'caza',
 'cincuenta',
 'como',
 'complexión',
 'con',
 'concluían',
 'conjeturas',
 'consumían',
 'corredor',
 'cuarenta',
 'cuento',
 'cuyo',
 'de',
 'decir',
 'deja',
 'della',
 'deste',
 'diferencia',
 'domingos',
 'duelos',
 'dél',
 'días',
 'edad',
 'el',
 'en',
 'enjuto',
 'ensillaba',
 'entender',
 'entresemana',
 'era',
 'escriben',
 'esto',
 'fiestas',
 'fino',
 'flaco',
 'galgo',
 'gran',
 'ha',
 'hacienda',
 'hay',
 'hidalgo',
 'honraba',
 'importa',
 'la',
 'lantejas',
 'lanza',
 'las',
 'llamaba',
 'llegaba',
 'lo',
 'los',
 'lugar',
 'madrugador',
 'mesmo',
 'mozo',
 'mucho',
 'más',
 'narración',
 'no',
 'noches',
 'nombre',
 'nuestro',
 'o',
 'olla',
 'palomino',
 'pantuflos',
 'para',
 'partes',
 'pasaba',
 'plaza',
 'poco',
 'podadera',
 'por',
 'punto',
 'que',
 'quebrantos',
 'quiero',
 'recia',
 'resto',
 'rocín',
 'rocón',
 'rostro',
 'salga',
 'salpicón',
 'sayo',
 'se',
 'seco',
 'sobrenombre',
 'sobrina',
 'su',
 'sus',
 'sábados',
 'tenía',
 'tiempo',
 'tomaba',
 'tres',
 'un',
 'una',
 'vaca',
 'veinte',
 'velarte',
 'vellorí',
 'velludo',
 'verdad',
 'verosímiles',
 'viernes',
 'vivía',
 'y'}

In [79]:
# Buscamos las palabras no repetidas del set en la variable de texto para poderlas contar
re.findall?

Signature: re.findall(pattern, string, flags=0)
Docstring:
Return a list of all non-overlapping matches in the string.

If one or more capturing groups are present in the pattern, return
a list of groups; this will be a list of tuples if the pattern
has more than one group.

Empty matches are included in the result.
File:      c:\users\uie70742\.conda\envs\ic_curso_2026\lib\re.py
Type:      function

In [ ]:
# En, en

In [80]:
re.findall('en',texto,flags=re.I)

['En',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en']

In [81]:
d={}
for palabra in S:
    d[palabra]=len(re.findall(palabra,texto,flags=re.I))
d

{'y': 10,
 'tres': 2,
 'sus': 1,
 'podadera': 1,
 'el': 8,
 'adarga': 1,
 'rocín': 1,
 'lugar': 1,
 'entender': 1,
 'diferencia': 1,
 'añadidura': 1,
 'poco': 1,
 'della': 1,
 'consumían': 1,
 'llamaba': 1,
 'partes': 1,
 'honraba': 1,
 'algo': 4,
 'hidalgo': 2,
 'vivía': 1,
 'se': 6,
 'esto': 3,
 'mozo': 1,
 'velarte': 1,
 'un': 10,
 'caza': 1,
 'salpicón': 1,
 'días': 1,
 'tiempo': 1,
 'aunque': 1,
 'de': 27,
 'casa': 1,
 'su': 5,
 'acordarme': 1,
 'seco': 1,
 'lantejas': 1,
 'fiestas': 1,
 'deste': 1,
 'viernes': 1,
 'resto': 1,
 'narración': 1,
 'años': 1,
 'olla': 1,
 'astillero': 1,
 'velludo': 1,
 'hacienda': 1,
 'carnero': 1,
 'pantuflos': 1,
 'los': 11,
 'dél': 1,
 'gran': 1,
 'escriben': 1,
 'cuyo': 1,
 'domingos': 1,
 'Frisaba': 1,
 'noches': 1,
 'quebrantos': 1,
 'era': 2,
 'madrugador': 1,
 'ama': 2,
 'lo': 15,
 'corredor': 1,
 'sábados': 1,
 'autores': 1,
 'campo': 1,
 'sobrenombre': 1,
 'o': 88,
 'Una': 4,
 'lanza': 1,
 'con': 6,
 'las': 3,
 'así': 1,
 'cuarenta': 1,
 'decir': 1,
 'ha': 4,
 'flaco': 1,
 'pasaba': 1,
 'quiero': 1,
 'vellorí': 1,
 'Quesada': 1,
 'carnes': 1,
 'basta': 1,
 'que': 13,
 'calzas': 1,
 'nuestro': 2,
 'Pero': 1,
 'como': 1,
 'Tenía': 2,
 'verosímiles': 1,
 'cuento': 1,
 'entresemana': 1,
 'palomino': 1,
 'Quijada': 1,
 'fino': 1,
 'llegaba': 1,
 'verdad': 1,
 'salga': 1,
 'enjuto': 1,
 'rostro': 1,
 'para': 1,
 'edad': 1,
 'vaca': 1,
 'veinte': 1,
 'plaza': 1,
 'no': 9,
 'galgo': 1,
 'cincuenta': 1,
 'amigo': 1,
 'ensillaba': 1,
 'la': 18,
 'recia': 1,
 'importa': 1,
 'nombre': 2,
 'por': 2,
 'rocón': 1,
 'a': 131,
 'En': 21,
 'mucho': 1,
 'antigua': 1,
 'punto': 1,
 'caso': 1,
 'duelos': 1,
 'una': 4,
 'sobrina': 1,
 'Mancha': 1,
 'complexión': 1,
 'El': 8,
 'concluían': 1,
 'mesmo': 1,
 'tomaba': 1,
 'tenía': 2,
 'más': 3,
 'Quieren': 1,
 'sayo': 1,
 'deja': 1,
 'hay': 1,
 'alguna': 1,
 'conjeturas': 1,
 'Quijana': 1,
 'en': 21,
 'algún': 1}

In [84]:
d.items()

dict_items([('y', 10), ('tres', 2), ('sus', 1), ('podadera', 1), ('el', 8), ('adarga', 1), ('rocín', 1), ('lugar', 1), ('entender', 1), ('diferencia', 1), ('añadidura', 1), ('poco', 1), ('della', 1), ('consumían', 1), ('llamaba', 1), ('partes', 1), ('honraba', 1), ('algo', 4), ('hidalgo', 2), ('vivía', 1), ('se', 6), ('esto', 3), ('mozo', 1), ('velarte', 1), ('un', 10), ('caza', 1), ('salpicón', 1), ('días', 1), ('tiempo', 1), ('aunque', 1), ('de', 27), ('casa', 1), ('su', 5), ('acordarme', 1), ('seco', 1), ('lantejas', 1), ('fiestas', 1), ('deste', 1), ('viernes', 1), ('resto', 1), ('narración', 1), ('años', 1), ('olla', 1), ('astillero', 1), ('velludo', 1), ('hacienda', 1), ('carnero', 1), ('pantuflos', 1), ('los', 11), ('dél', 1), ('gran', 1), ('escriben', 1), ('cuyo', 1), ('domingos', 1), ('Frisaba', 1), ('noches', 1), ('quebrantos', 1), ('era', 2), ('madrugador', 1), ('ama', 2), ('lo', 15), ('corredor', 1), ('sábados', 1), ('autores', 1), ('campo', 1), ('sobrenombre', 1), ('o', 88), ('Una', 4), ('lanza', 1), ('con', 6), ('las', 3), ('así', 1), ('cuarenta', 1), ('decir', 1), ('ha', 4), ('flaco', 1), ('pasaba', 1), ('quiero', 1), ('vellorí', 1), ('Quesada', 1), ('carnes', 1), ('basta', 1), ('que', 13), ('calzas', 1), ('nuestro', 2), ('Pero', 1), ('como', 1), ('Tenía', 2), ('verosímiles', 1), ('cuento', 1), ('entresemana', 1), ('palomino', 1), ('Quijada', 1), ('fino', 1), ('llegaba', 1), ('verdad', 1), ('salga', 1), ('enjuto', 1), ('rostro', 1), ('para', 1), ('edad', 1), ('vaca', 1), ('veinte', 1), ('plaza', 1), ('no', 9), ('galgo', 1), ('cincuenta', 1), ('amigo', 1), ('ensillaba', 1), ('la', 18), ('recia', 1), ('importa', 1), ('nombre', 2), ('por', 2), ('rocón', 1), ('a', 131), ('En', 21), ('mucho', 1), ('antigua', 1), ('punto', 1), ('caso', 1), ('duelos', 1), ('una', 4), ('sobrina', 1), ('Mancha', 1), ('complexión', 1), ('El', 8), ('concluían', 1), ('mesmo', 1), ('tomaba', 1), ('tenía', 2), ('más', 3), ('Quieren', 1), ('sayo', 1), ('deja', 1), ('hay', 1), ('alguna', 1), ('conjeturas', 1), ('Quijana', 1), ('en', 21), ('algún', 1)])

In [82]:
df=pd.DataFrame(d.items(),columns=['Palabra','No.'])

In [83]:
df.head()

    Palabra  No.
0         y   10
1      tres    2
2       sus    1
3  podadera    1
4        el    8

https://regex101.com/

# 4. Archivos Excel

Excel puede contener varias hojas, fórmulas, índices y celdas de presentación. Al extraer datos, distingue la hoja que contiene la tabla de las filas de título o notas que sirven para lectura humana.

`pd.read_excel` es conveniente para leer directamente una hoja. `ExcelFile` resulta útil cuando se desea inspeccionar o reutilizar un libro con varias hojas sin abrirlo repetidamente.

> **Buenas prácticas:** registra el nombre de la hoja, comprueba los encabezados y convierte explícitamente fechas y números cuando Excel los haya interpretado de forma ambigua.

In [85]:
# A partir de la función
pd.read_excel(ruta+'API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls')

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,Last Updated Date,2020-12-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
3,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,Kosovo,XKX,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,1.7,0.6,0.3,1.0,0.7,0.8,0.4,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.3,NaN,NaN,NaN,NaN,NaN,NaN
264,South Africa,ZAF,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.7,NaN,NaN,NaN,NaN,NaN,NaN
265,Zambia,ZMB,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,58.7,NaN,NaN,NaN,NaN,NaN
266,Zimbabwe,ZWE,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,NaN,NaN,NaN,NaN,NaN,33.9,NaN,NaN,NaN

In [86]:
# Importamos la clase ExcelFile
from pandas import ExcelFile

In [87]:
# A partir de la clase
obj=ExcelFile(ruta+'API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls')
obj.parse() # Importa la primera página

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,Last Updated Date,2020-12-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
3,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,Kosovo,XKX,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,1.7,0.6,0.3,1.0,0.7,0.8,0.4,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.3,NaN,NaN,NaN,NaN,NaN,NaN
264,South Africa,ZAF,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.7,NaN,NaN,NaN,NaN,NaN,NaN
265,Zambia,ZMB,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,58.7,NaN,NaN,NaN,NaN,NaN
266,Zimbabwe,ZWE,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,NaN,NaN,NaN,NaN,NaN,33.9,NaN,NaN,NaN

In [88]:
help(obj.parse)

Help on method parse in module pandas.io.excel._base:

parse(sheet_name: 'str | int | list[int] | list[str] | None' = 0, header: 'int | Sequence[int] | None' = 0, names: 'SequenceNotStr[Hashable] | range | None' = None, index_col: 'int | Sequence[int] | None' = None, usecols=None, converters=None, true_values: 'Iterable[Hashable] | None' = None, false_values: 'Iterable[Hashable] | None' = None, skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None, nrows: 'int | None' = None, na_values=None, parse_dates: 'list | dict | bool' = False, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, thousands: 'str | None' = None, comment: 'str | None' = None, skipfooter: 'int' = 0, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>, **kwds) -> 'DataFrame | dict[str, DataFrame] | dict[int, DataFrame]' method of pandas.io.excel._base.ExcelFile instance
    Parse specified sheet(s) into a DataFrame.

    Equivalent to read_excel(ExcelFile, ...)  See the read_excel
    docstring for more info on accepted parameters.

    Returns
    -------
    DataFrame or dict of DataFrames
        DataFrame from the passed in Excel file.

    Examples
    --------
    >>> df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=['A', 'B', 'C'])
    >>> df.to_excel('myfile.xlsx')  # doctest: +SKIP
    >>> file = pd.ExcelFile('myfile.xlsx')  # doctest: +SKIP
    >>> file.parse()  # doctest: +SKIP

In [90]:
obj.sheet_names

['Data', 'Metadata - Countries', 'Metadata - Indicators']

In [92]:
df_data = obj.parse('Data', header=3)
df_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.8,NaN,NaN
3,Albania,ALB,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.8,NaN,1.6,1.1,0.9,1.3,NaN,NaN,NaN
4,Andorra,AND,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,1.7,0.6,0.3,1.0,0.7,0.8,0.4,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.3,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.7,NaN,NaN,NaN,NaN,NaN,NaN
262,Zambia,ZMB,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,58.7,NaN,NaN,NaN,NaN,NaN
263,Zimbabwe,ZWE,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,NaN,NaN,NaN,NaN,NaN,33.9,NaN,NaN,NaN

In [93]:
df_paises = obj.parse('Metadata - Countries')
df_paises

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFG,South Asia,Low income,NaN,Afghanistan
2,AGO,Sub-Saharan Africa,Lower middle income,NaN,Angola
3,ALB,Europe & Central Asia,Upper middle income,NaN,Albania
4,AND,Europe & Central Asia,High income,NaN,Andorra
...,...,...,...,...,...
258,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
259,YEM,Middle East & North Africa,Low income,NaN,"Yemen, Rep."
260,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
261,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
262,ZWE,Sub-Saharan Africa,Lower middle income,NaN,Zimbabwe

In [94]:
df_dict = {}
for data in obj.sheet_names:
    df_dict[data] = obj.parse(data)

In [96]:
df_dict['Data']

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,Last Updated Date,2020-12-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0
3,Aruba,ABW,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,Kosovo,XKX,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,1.7,0.6,0.3,1.0,0.7,0.8,0.4,NaN,NaN,NaN
263,"Yemen, Rep.",YEM,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.3,NaN,NaN,NaN,NaN,NaN,NaN
264,South Africa,ZAF,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.7,NaN,NaN,NaN,NaN,NaN,NaN
265,Zambia,ZMB,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,58.7,NaN,NaN,NaN,NaN,NaN
266,Zimbabwe,ZWE,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,NaN,NaN,NaN,NaN,NaN,33.9,NaN,NaN,NaN

# 5. Archivos JSON

JSON representa datos mediante pares `clave: valor`, listas y objetos anidados. Es muy habitual en APIs, configuraciones y registros de aplicaciones porque conserva mejor la estructura que una tabla plana.

El proceso tiene dos etapas: `json.load` o `json.loads` convierte el contenido a diccionarios y listas de Python; después, `json_normalize` ayuda a convertir objetos repetidos o anidados en columnas de un DataFrame. No todos los JSON tienen la misma forma, por lo que primero conviene inspeccionar sus claves y niveles.

El formato JSON (JavaScript Object Notation) es ampliamente utilizado para el intercambio de datos, especialmente en aplicaciones web y APIs. Python incluye la librería estándar `json` para leer y manipular archivos JSON.

In [97]:
import json

json_data = '{"personas": [{"nombre": "Ana", "edad": 23}, {"nombre": "Luis", "edad": 31}]}'
data = json.loads(json_data)
print('Personas extraídas del archivo JSON:')
for persona in data['personas']:
    print(f'Nombre: {persona["nombre"]}, Edad: {persona["edad"]}')

Personas extraídas del archivo JSON:
Nombre: Ana, Edad: 23
Nombre: Luis, Edad: 31

In [98]:
from pandas import json_normalize

with open('Data/data.json') as jsonfile:
    jsondata = json.load(jsonfile)
    
df_json = json_normalize(jsondata['data'])
df_json

,_id,categories,isActive,imageUrl,barcode,isFmcg,itemName,mrp,_created_at,_updated_at
0,OzE5vaa3p7,"[{'__type': 'Pointer', 'className': 'Category'...",True,https://firebasestorage.googleapis.com/v0/b/sh...,8908001921015,True,Anil puttu flour 500g,58,2016-10-02T13:49:03.281Z,2017-02-22T08:48:09.548Z
1,ENPCL8ph1p,"[{'__type': 'Pointer', 'className': 'Category'...",True,https://firebasestorage.googleapis.com/v0/b/ki...,8901725181222,True,"Yippee Magic Masala Noodles, 70 G",12,2016-10-02T13:49:03.284Z,2017-02-22T08:48:09.074Z

In [99]:
df_json['categories'][0]

[{'__type': 'Pointer', 'className': 'Category', 'objectId': 'nebCwWd2Fr'}]

# 6. Archivos XML

XML organiza la información como un árbol de elementos. Cada nodo puede tener una etiqueta, atributos, texto y nodos hijos. Esta jerarquía permite representar relaciones complejas, aunque requiere recorrer el árbol para llegar a los valores.

En los ejemplos se usan dos enfoques: `find`/`findall` para rutas conocidas y recorridos anidados cuando se necesita explorar la estructura. Al convertir XML a tabla hay que decidir qué nodo representa una fila y cómo tratar los elementos que faltan o se repiten.

El formato XML es común para el intercambio de datos estructurados. Python ofrece la librería estándar `xml.etree.ElementTree` para analizar y extraer información de archivos XML.

In [100]:
import xml.etree.ElementTree as ET

In [101]:
xml_data = '''
<personas>
  <persona>
    <nombre>Ana</nombre>
    <edad>23</edad>
  </persona>
  <persona>
    <nombre>Luis</nombre>
    <edad>31</edad>
  </persona>
</personas>
'''

In [102]:

root = ET.fromstring(xml_data)
print('Personas extraídas del archivo XML:')
for persona in root.findall('persona'):
    nombre = persona.find('nombre').text
    edad = persona.find('edad').text
    print(f'Nombre: {nombre}, Edad: {edad}')

Personas extraídas del archivo XML:
Nombre: Ana, Edad: 23
Nombre: Luis, Edad: 31

###### Ejemplo con tabla_1.xml

In [103]:
archivo_1=ET.parse(ruta+'tabla_1.xml')
raiz=archivo_1.getroot()

In [104]:
raiz

In [105]:
for nodo in raiz:
    print(nodo.attrib,nodo.text,nodo.tag)
    for sn in nodo:
        print(sn.attrib,sn.text,sn.tag)

{'name': 'Liechtenstein'}
         country
{} 1 rank
{} 2008 year
{} 141100 gdppc
{'name': 'Singapore'}
         country
{} 4 rank
{} 2011 year
{} 59900 gdppc
{'name': 'Panama'}
         country
{} 68 rank
{} 2011 year
{} 13600 gdppc

In [107]:
archivo_2=ET.parse(ruta+'tabla_2.xml')
root=archivo_2.getroot()
for nodo in root:
    print(nodo.tag,nodo.attrib,nodo.text)

documents {'count': 'N'}

In [108]:
for nodo in root:
    for subn in nodo:
        print(subn.tag,subn.attrib,subn.text)

document {'KEY': 'e95a9a6c790ecb95e46cf15bee517651', 'web': 'www.ubm/doc004.com'} Nevertheless, high and based on experience, fluctuating throughput levels contradict high reliability.


document {'KEY': 'bc360cfbafc39970587547215162f0db', 'web': 'www.ubm/doc006.com'} As long as the production is not conducted on the basis of concrete customer orders, the companies objectives


document {'KEY': '19e71144c50a8b9160b3f0955e906fce', 'web': 'www.ubm/doc005.com'} Many companies today, in different fields of operations and sizes, have access to a vast amount of data which was not available only a couple of years ago.


document {'KEY': '21d4af9021a174f61b884606c74d9e42', 'web': 'www.ubm/doc002.com'} A famous example of a successful prediction is by the German astronomer Johann Gottfried Galle


document {'KEY': '28a45eb2460899763d709ca00ddbb665', 'web': 'www.ubm/doc001.com'} A more recent example of the same kind is the prediction of the Higgs boson by Francois Englert and Peter Higgs

In [109]:
#Extraer los datos de tabla_1.xml
d={}
for nodo in raiz:
    d[nodo.tag]=[]
for nodo in raiz:
    d[nodo.tag].append(nodo.attrib['name'])
for nodo in raiz:
    for sn in nodo:
        d[sn.tag]=[]
for nodo in raiz:
    for sn in nodo:
        d[sn.tag].append(sn.text)
d

{'country': ['Liechtenstein', 'Singapore', 'Panama'],
 'rank': ['1', '4', '68'],
 'year': ['2008', '2011', '2011'],
 'gdppc': ['141100', '59900', '13600']}

In [110]:
pd.DataFrame(d)

         country rank  year   gdppc
0  Liechtenstein    1  2008  141100
1      Singapore    4  2011   59900
2         Panama   68  2011   13600

```python
df_1 = pd.DataFrame(columns = columnas)
for nodo in raiz:
  L = []
  L.append(nodo.attrib['name'])
  for sn in nodo:
    L.append(sn.text)
  df_1 = df_1.append(pd.DataFrame([L], columns=columnas), ignore_index=True)
```

In [111]:
archivo=ET.parse(ruta+'tabla_2.xml')
raiz=archivo.getroot()

In [112]:
L=[]
for n in raiz.findall('documents/document'):
    d={}
    d[n.tag]=n.text
    for k,v in n.attrib.items():
        d[k]=v
    L.append(d)
pd.DataFrame(L)

,document,KEY,web
0,"Nevertheless, high and based on experience, fl...",e95a9a6c790ecb95e46cf15bee517651,www.ubm/doc004.com
1,As long as the production is not conducted on ...,bc360cfbafc39970587547215162f0db,www.ubm/doc006.com
2,"Many companies today, in different fields of o...",19e71144c50a8b9160b3f0955e906fce,www.ubm/doc005.com
3,A famous example of a successful prediction is...,21d4af9021a174f61b884606c74d9e42,www.ubm/doc002.com
4,A more recent example of the same kind is the ...,28a45eb2460899763d709ca00ddbb665,www.ubm/doc001.com

In [113]:
L

[{'document': 'Nevertheless, high and based on experience, fluctuating throughput levels contradict high reliability.\n\n        ',
  'KEY': 'e95a9a6c790ecb95e46cf15bee517651',
  'web': 'www.ubm/doc004.com'},
 {'document': 'As long as the production is not conducted on the basis of concrete customer orders, the companies objectives\n\n        ',
  'KEY': 'bc360cfbafc39970587547215162f0db',
  'web': 'www.ubm/doc006.com'},
 {'document': 'Many companies today, in different fields of operations and sizes, have access to a vast amount of data which was not available only a couple of years ago.\n\n        ',
  'KEY': '19e71144c50a8b9160b3f0955e906fce',
  'web': 'www.ubm/doc005.com'},
 {'document': 'A famous example of a successful prediction is by the German astronomer Johann Gottfried Galle\n\n        ',
  'KEY': '21d4af9021a174f61b884606c74d9e42',
  'web': 'www.ubm/doc002.com'},
 {'document': 'A more recent example of the same kind is the prediction of the Higgs boson by Francois Englert and Peter Higgs\n\n        ',
  'KEY': '28a45eb2460899763d709ca00ddbb665',
  'web': 'www.ubm/doc001.com'}]

---

In [114]:
archivo='IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml'
file=ET.parse(ruta+archivo)
root=file.getroot()

for nodo in root:
    for snodo in nodo:
        print(snodo.tag,snodo.attrib,snodo.text)
        for ssnodo in snodo:
            print(ssnodo.tag,ssnodo.attrib,ssnodo.text)

row {'_id': 'row-y44j~at3a-b2ir', '_uuid': '00000000-0000-0000-0100-063657E78388', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-y44j~at3a-b2ir'}

member {} Afghanistan
amount_thousands_of_usd {} 1727
percent_of_total_amount {} 0.01
number_of_votes {} 8326
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-cgqt~xxg3~xehh', '_uuid': '00000000-0000-0000-028B-9164C4785E6F', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-cgqt~xxg3~xehh'}

member {} Albania
amount_thousands_of_usd {} 9927
percent_of_total_amount {} 0.05
number_of_votes {} 16526
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-q7xr_qk5p_hqh3', '_uuid': '00000000-0000-0000-E37B-CAECEC3A0C26', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-q7xr_qk5p_hqh3'}

member {} Algeria
amount_thousands_of_usd {} 51116
percent_of_total_amount {} 0.25
number_of_votes {} 57715
percent_of_total_votes {} 0.26
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-u2xu-enky.kggg', '_uuid': '00000000-0000-0000-5E03-D3BA6F640E74', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-u2xu-enky.kggg'}

member {} Angola
amount_thousands_of_usd {} 11292
percent_of_total_amount {} 0.05
number_of_votes {} 17891
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-j7ts~ti34_3pcy', '_uuid': '00000000-0000-0000-2FA7-DDD7B7C43943', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-j7ts~ti34_3pcy'}

member {} Antigua and Barbuda
amount_thousands_of_usd {} 99
percent_of_total_amount {} 0.00
number_of_votes {} 6698
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-geqr.hf5b~pme8', '_uuid': '00000000-0000-0000-7BA7-A38C9799858F', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-geqr.hf5b~pme8'}

member {} Argentina
amount_thousands_of_usd {} 323320
percent_of_total_amount {} 1.56
number_of_votes {} 329919
percent_of_total_votes {} 1.50
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-vct9-gbrd-kdsk', '_uuid': '00000000-0000-0000-6EAF-7A4ED7CD8724', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-vct9-gbrd-kdsk'}

member {} Armenia
amount_thousands_of_usd {} 7564
percent_of_total_amount {} 0.04
number_of_votes {} 14163
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-6tcz.psxe~p4jx', '_uuid': '00000000-0000-0000-F0C9-F90D050B348E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-6tcz.psxe~p4jx'}

member {} Australia
amount_thousands_of_usd {} 401814
percent_of_total_amount {} 1.93
number_of_votes {} 408413
percent_of_total_votes {} 1.86
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-phnu-yhin.6pnb', '_uuid': '00000000-0000-0000-417A-87B21F7C5B8C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-phnu-yhin.6pnb'}

member {} Austria
amount_thousands_of_usd {} 161192
percent_of_total_amount {} 0.78
number_of_votes {} 167791
percent_of_total_votes {} 0.76
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-iysh_uwu8-mbrd', '_uuid': '00000000-0000-0000-1906-7E92EA2CCF37', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-iysh_uwu8-mbrd'}

member {} Azerbaijan
amount_thousands_of_usd {} 18047
percent_of_total_amount {} 0.09
number_of_votes {} 24646
percent_of_total_votes {} 0.11
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-scnb~mk4h~atcb', '_uuid': '00000000-0000-0000-59DE-84BD2BD2B4F1', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-scnb~mk4h~atcb'}

member {} Bahamas, The
amount_thousands_of_usd {} 2554
percent_of_total_amount {} 0.01
number_of_votes {} 9153
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-eyn7-p3d5_itvt', '_uuid': '00000000-0000-0000-36D6-7172B1E2CB50', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-eyn7-p3d5_itvt'}

member {} Bahrain
amount_thousands_of_usd {} 13313
percent_of_total_amount {} 0.06
number_of_votes {} 19912
percent_of_total_votes {} 0.09
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-5xhz.y8aw~7cxx', '_uuid': '00000000-0000-0000-875E-BF9163FCCF6A', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-5xhz.y8aw~7cxx'}

member {} Bangladesh
amount_thousands_of_usd {} 73440
percent_of_total_amount {} 0.35
number_of_votes {} 80039
percent_of_total_votes {} 0.36
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-n3r2-n8gv.pxn6', '_uuid': '00000000-0000-0000-EF34-D5E63E4E2957', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-n3r2-n8gv.pxn6'}

member {} Barbados
amount_thousands_of_usd {} 2752
percent_of_total_amount {} 0.01
number_of_votes {} 9351
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-z3fe~yh2x.bb2p', '_uuid': '00000000-0000-0000-E432-4A628F933E8E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-z3fe~yh2x.bb2p'}

member {} Belarus
amount_thousands_of_usd {} 40159
percent_of_total_amount {} 0.19
number_of_votes {} 46758
percent_of_total_votes {} 0.21
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-2mi8-vkvt-tqge', '_uuid': '00000000-0000-0000-0A2F-917771F88F2B', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-2mi8-vkvt-tqge'}

member {} Belgium
amount_thousands_of_usd {} 385880
percent_of_total_amount {} 1.86
number_of_votes {} 392479
percent_of_total_votes {} 1.78
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-wp9x_9cwt-y9zb', '_uuid': '00000000-0000-0000-47BB-629CA09F772C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-wp9x_9cwt-y9zb'}

member {} Belize
amount_thousands_of_usd {} 770
percent_of_total_amount {} 0.00
number_of_votes {} 7369
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-bsru.bbwf-ce4z', '_uuid': '00000000-0000-0000-6248-BB06A9602EDE', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-bsru.bbwf-ce4z'}

member {} Benin
amount_thousands_of_usd {} 907
percent_of_total_amount {} 0.00
number_of_votes {} 7506
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-v26i.tv2s_8daq', '_uuid': '00000000-0000-0000-A8DE-812509DB753E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-v26i.tv2s_8daq'}

member {} Bhutan
amount_thousands_of_usd {} 5490
percent_of_total_amount {} 0.03
number_of_votes {} 12089
percent_of_total_votes {} 0.05
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-d5pv_crx5-fm6f', '_uuid': '00000000-0000-0000-69F9-2DC06374EF0A', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-d5pv_crx5-fm6f'}

member {} Bolivia
amount_thousands_of_usd {} 14502
percent_of_total_amount {} 0.07
number_of_votes {} 21101
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-ufhx.da26-85rt', '_uuid': '00000000-0000-0000-7C74-E38640986EB9', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-ufhx.da26-85rt'}

member {} Bosnia and Herzegovina
amount_thousands_of_usd {} 5921
percent_of_total_amount {} 0.03
number_of_votes {} 12520
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-zgfu.kw8d.8vwb', '_uuid': '00000000-0000-0000-55E7-0776E0377EF5', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-zgfu.kw8d.8vwb'}

member {} Botswana
amount_thousands_of_usd {} 862
percent_of_total_amount {} 0.00
number_of_votes {} 7461
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-73fr~axud.mhv8', '_uuid': '00000000-0000-0000-AD45-ABDD1076201E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-73fr~axud.mhv8'}

member {} Brazil
amount_thousands_of_usd {} 423812
percent_of_total_amount {} 2.04
number_of_votes {} 430411
percent_of_total_votes {} 1.96
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-4ymb-7kxa_sj6r', '_uuid': '00000000-0000-0000-7B78-0C506B6CC088', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-4ymb-7kxa_sj6r'}

member {} Bulgaria
amount_thousands_of_usd {} 37620
percent_of_total_amount {} 0.18
number_of_votes {} 44219
percent_of_total_votes {} 0.20
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-hpiq.kk3z_uk8d', '_uuid': '00000000-0000-0000-1DFF-B1E7BC4A0A1D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-hpiq.kk3z_uk8d'}

member {} Burkina Faso
amount_thousands_of_usd {} 6374
percent_of_total_amount {} 0.03
number_of_votes {} 12973
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-zkk3-ftyx_gura', '_uuid': '00000000-0000-0000-E564-806375DE2E2C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-zkk3-ftyx_gura'}

member {} Burundi
amount_thousands_of_usd {} 762
percent_of_total_amount {} 0.00
number_of_votes {} 7361
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-xsde-q2r3~psrk', '_uuid': '00000000-0000-0000-F129-A2A9F6F5A1D3', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-xsde-q2r3~psrk'}

member {} CABO VERDE
amount_thousands_of_usd {} 114
percent_of_total_amount {} 0.00
number_of_votes {} 6713
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-stm5-kuzv-vi7a', '_uuid': '00000000-0000-0000-4219-18A62E093D4D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-stm5-kuzv-vi7a'}

member {} Cambodia
amount_thousands_of_usd {} 2585
percent_of_total_amount {} 0.01
number_of_votes {} 9184
percent_of_total_votes {} 0.04
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-ycht.7a4c-4ke5', '_uuid': '00000000-0000-0000-A362-2992318BAB44', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-ycht.7a4c-4ke5'}

member {} Cameroon
amount_thousands_of_usd {} 6748
percent_of_total_amount {} 0.03
number_of_votes {} 13347
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-xgga.szsn-b94e', '_uuid': '00000000-0000-0000-D9BB-F2EC2DD11E0E', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-xgga.szsn-b94e'}

member {} Canada
amount_thousands_of_usd {} 620199
percent_of_total_amount {} 2.99
number_of_votes {} 626798
percent_of_total_votes {} 2.85
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-tpu8~fvfm-x5id', '_uuid': '00000000-0000-0000-89F0-6B7E8D3717DA', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-tpu8~fvfm-x5id'}

member {} Central African Republic
amount_thousands_of_usd {} 907
percent_of_total_amount {} 0.00
number_of_votes {} 7506
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-2b2v.4hsh-7tsp', '_uuid': '00000000-0000-0000-0271-ADE02734B662', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-2b2v.4hsh-7tsp'}

member {} Chad
amount_thousands_of_usd {} 10400
percent_of_total_amount {} 0.05
number_of_votes {} 16999
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-2v3b~ybi4_7ew2', '_uuid': '00000000-0000-0000-E241-E6B829A3A2DC', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-2v3b~ybi4_7ew2'}

member {} Chile
amount_thousands_of_usd {} 96428
percent_of_total_amount {} 0.46
number_of_votes {} 103027
percent_of_total_votes {} 0.47
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-c6bi~ct9y.9c4d', '_uuid': '00000000-0000-0000-873A-6B18AA78F685', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-c6bi~ct9y.9c4d'}

member {} China
amount_thousands_of_usd {} 470864
percent_of_total_amount {} 2.27
number_of_votes {} 477463
percent_of_total_votes {} 2.17
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-mkxt.iw8x-m6ip', '_uuid': '00000000-0000-0000-6558-5D0623BE5649', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-mkxt.iw8x-m6ip'}

member {} Colombia
amount_thousands_of_usd {} 104137
percent_of_total_amount {} 0.50
number_of_votes {} 110736
percent_of_total_votes {} 0.50
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-ddiz_pfz8_kvdr', '_uuid': '00000000-0000-0000-773D-D0AB05484411', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-ddiz_pfz8_kvdr'}

member {} Comoros
amount_thousands_of_usd {} 107
percent_of_total_amount {} 0.00
number_of_votes {} 6706
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-p2wp~3f9z.9n4s', '_uuid': '00000000-0000-0000-74D4-0895CBD6404D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-p2wp~3f9z.9n4s'}

member {} Congo, Democratic Republic of
amount_thousands_of_usd {} 16461
percent_of_total_amount {} 0.08
number_of_votes {} 23060
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-tg2s.x2v7-xkaz', '_uuid': '00000000-0000-0000-C974-FBED0584B453', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-tg2s.x2v7-xkaz'}

member {} Congo, Republic of
amount_thousands_of_usd {} 999
percent_of_total_amount {} 0.00
number_of_votes {} 7598
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-3bpt-dke2~34t6', '_uuid': '00000000-0000-0000-C865-05C9AC41D473', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-3bpt-dke2~34t6'}

member {} Costa Rica
amount_thousands_of_usd {} 7259
percent_of_total_amount {} 0.03
number_of_votes {} 13858
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-n3p9.7qtq.saxj', '_uuid': '00000000-0000-0000-E4E8-2E7F7C925294', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-n3p9.7qtq.saxj'}

member {} Cote d'Ivoire
amount_thousands_of_usd {} 29443
percent_of_total_amount {} 0.14
number_of_votes {} 36042
percent_of_total_votes {} 0.16
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-wm44-8kgr.7wkm', '_uuid': '00000000-0000-0000-7F42-D8273C36CB7B', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-wm44-8kgr.7wkm'}

member {} Croatia
amount_thousands_of_usd {} 23384
percent_of_total_amount {} 0.11
number_of_votes {} 29983
percent_of_total_votes {} 0.14
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-m6x4.kdiw.69zs', '_uuid': '00000000-0000-0000-2957-4028107E2241', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-m6x4.kdiw.69zs'}

member {} Cyprus
amount_thousands_of_usd {} 16309
percent_of_total_amount {} 0.08
number_of_votes {} 22908
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-f6g7_7p38-dybb', '_uuid': '00000000-0000-0000-4D7E-CA71479B6D36', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-f6g7_7p38-dybb'}

member {} Czech Republic
amount_thousands_of_usd {} 79076
percent_of_total_amount {} 0.38
number_of_votes {} 85675
percent_of_total_votes {} 0.39
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-u2ng~t3mx_tnu8', '_uuid': '00000000-0000-0000-ABCC-34980FD6D807', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-u2ng~t3mx_tnu8'}

member {} Denmark
amount_thousands_of_usd {} 170267
percent_of_total_amount {} 0.82
number_of_votes {} 176866
percent_of_total_votes {} 0.80
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-kyyk_gxde.jq9b', '_uuid': '00000000-0000-0000-E2EB-2DDF316C2B08', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-kyyk_gxde.jq9b'}

member {} Djibouti
amount_thousands_of_usd {} 160
percent_of_total_amount {} 0.00
number_of_votes {} 6759
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-gz3e.hnc2.ymxw', '_uuid': '00000000-0000-0000-1288-F3C5A6A68C1C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-gz3e.hnc2.ymxw'}

member {} Dominica
amount_thousands_of_usd {} 320
percent_of_total_amount {} 0.00
number_of_votes {} 6919
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-79zk.2amz~vmfd', '_uuid': '00000000-0000-0000-3057-0E32AE875166', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-79zk.2amz~vmfd'}

member {} Dominican Republic
amount_thousands_of_usd {} 9050
percent_of_total_amount {} 0.04
number_of_votes {} 15649
percent_of_total_votes {} 0.07
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-63k4.qbpc-6gbp', '_uuid': '00000000-0000-0000-4AE8-074983F41E18', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-63k4.qbpc-6gbp'}

member {} Ecuador
amount_thousands_of_usd {} 16477
percent_of_total_amount {} 0.08
number_of_votes {} 23076
percent_of_total_votes {} 0.10
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-9izi.fybb-gmxz', '_uuid': '00000000-0000-0000-7A24-32F1458F6D78', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-9izi.fybb-gmxz'}

member {} Egypt, Arab Republic of
amount_thousands_of_usd {} 102017
percent_of_total_amount {} 0.49
number_of_votes {} 108616
percent_of_total_votes {} 0.49
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-rxn5_w92m~pdhf', '_uuid': '00000000-0000-0000-F246-3CF940C3ABD8', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-rxn5_w92m~pdhf'}

member {} El Salvador
amount_thousands_of_usd {} 221
percent_of_total_amount {} 0.00
number_of_votes {} 6820
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-pjuk-v9s8.y8vv', '_uuid': '00000000-0000-0000-8A7D-1F2E86537DE4', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-pjuk-v9s8.y8vv'}

member {} Equatorial Guinea
amount_thousands_of_usd {} 328
percent_of_total_amount {} 0.00
number_of_votes {} 6927
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-7rsr.82wk-dvyy', '_uuid': '00000000-0000-0000-2A52-A234F7812BAD', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-7rsr.82wk-dvyy'}

member {} Eritrea
amount_thousands_of_usd {} 7129
percent_of_total_amount {} 0.03
number_of_votes {} 13728
percent_of_total_votes {} 0.06
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-wbxk_k9g8_nvnn', '_uuid': '00000000-0000-0000-2CE7-1C9C19802E2D', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-wbxk_k9g8_nvnn'}

member {} Estonia
amount_thousands_of_usd {} 10934
percent_of_total_amount {} 0.05
number_of_votes {} 17533
percent_of_total_votes {} 0.08
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-7uis_mfuf~dznq', '_uuid': '00000000-0000-0000-F627-4E10E2962C1C', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-7uis_mfuf~dznq'}

member {} ESWATINI
amount_thousands_of_usd {} 5215
percent_of_total_amount {} 0.03
number_of_votes {} 11814
percent_of_total_votes {} 0.05
as_of_date {} 2021-08-06T00:00:00
row {'_id': 'row-qasr.4kha.btve', '_uuid': '00000000-0000-0000-DB1A-00E7458ED3D6', '_position': '0', '_address': 'https://finances.worldbank.org/resource/gsdw-avpz/row-qasr.4kha.btve'}

member {} Ethiopia
amount_thousands_of_usd {} 968
percent_of_total_amount {} 0.00
number_of_votes {} 7567
percent_of_total_votes {} 0.03
as_of_date {} 2021-08-06T00:00:00

---

# 7. Archivos SHP

Los archivos Shapefile (`.shp`) almacenan geometrías vectoriales, como puntos, líneas o polígonos, junto con atributos descriptivos. En realidad forman un conjunto de archivos relacionados: `.shp` guarda la geometría, `.shx` el índice espacial y `.dbf` los atributos; el `.prj` describe el sistema de coordenadas cuando está presente.

`geopandas` extiende `pandas` con una columna `geometry` y un sistema de referencia espacial (`crs`). Antes de calcular distancias o superponer capas, verifica que las capas estén en un CRS adecuado: los grados de latitud/longitud no son unidades lineales.

La librería `geopandas` permite leer y manipular estos archivos de forma parecida a un DataFrame, pero manteniendo la geometría. La visualización temática del ejemplo colorea cada geometría usando una columna de atributos; esto ayuda a comprobar que la tabla y el mapa se alinean.

> **Nota de instalación:** las celdas de instalación se conservan como referencia. En un entorno compartido es preferible instalar dependencias una sola vez y fijar sus versiones en `environment.yml` o `requirements.txt`.

In [ ]:
!pip install geopandas

In [ ]:
#!pip install geopandas

In [ ]:
# %conda !pip !conda
%pip install geopandas

In [ ]:
import geopandas as gpd

In [ ]:
g_df = gpd.read_file('COVID_INDIA_POC-shp/COVID_INDIA_POC.shp')
g_df

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(12, 8))
g_df.plot(
    ax=ax,
    column=g_df.columns[0],  # Cambia por la columna que quieras destacar
    cmap='viridis',
    edgecolor='black',
    legend=True
)
ax.set_title('COVID_INDIA_POC', fontsize=12)
ax.axis('off')
plt.show()
```

# 8. Archivos HTML y web scraping

HTML describe la estructura de una página mediante etiquetas y atributos. La extracción puede hacerse desde un archivo local o desde una URL, pero en ambos casos conviene separar tres tareas: descargar o abrir el documento, analizar su árbol y seleccionar los elementos que contienen los datos.

`BeautifulSoup` facilita la navegación del HTML. En sitios reales, los selectores pueden cambiar, existir contenido generado con JavaScript o aplicarse restricciones de uso; por eso hay que revisar los términos del sitio, limitar las solicitudes y comprobar que los datos extraídos sean completos.

In [ ]:
# Leer un archivo HTML local
with open(ruta+'ejemplo.html', 'r', encoding='utf-8') as file:
    html_content = file.read()
print(html_content[:500])  # Muestra los primeros 500 caracteres

In [ ]:
#!pip install beautifulsoup4 #Instalar BeautifulSoup si es necesario

In [ ]:
# Analizar HTML con BeautifulSoup
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Extraer el título de la página
titulo = soup.title.string
print('Título de la página:', titulo)

In [ ]:
# Extraer los enlaces de la página
enlaces = soup.find_all('a')
for enlace in enlaces:
    print(enlace.get('href'))

In [ ]:
#!pip install requests # Instalar requests si es necesario
import requests

url = 'https://www.python.org/'
response = requests.get(url)
web_html = response.text

# Analizar el HTML descargado
soup_web = BeautifulSoup(web_html, 'html.parser')

In [ ]:
print(soup_web.title)

###### Ejemplo sencillo webscraping

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
 
url = "https://codedamn-classrooms.github.io/webscraper-python-codedamn-classroom-website/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
type(soup)

In [ ]:
#Obtener un dataframe con la información de los productos
products = []

for price_tag in soup.find_all("h4", string=lambda s: s and s.strip().startswith("$")):
    # El nombre del producto es la cadena que sigue después del tag <a> después del precio
    product_link = price_tag.find_next("a")
    if not product_link:
        continue
    product_name = product_link.text.strip()
    product_url = product_link["href"]
    # La descripción es el siguien tag <p> después de la liga del producto
    description_tag = product_link.find_next("p")
    description = description_tag.text.strip() if description_tag else ""
    # Los numero de reviews van después de <div> 
    reviews_tag = product_link.find_next(string=lambda s: s and "review" in s)
    try:
        reviews = int(reviews_tag.strip().split()[0])
    except Exception:
        reviews = None
    # Precio
    try:
        price = float(price_tag.text.strip().replace("$", ""))
    except Exception:
        price = None
 
    products.append({
        "Product Name": product_name,
        "Price": price,
        "Description": description,
        "Reviews": reviews,
        "Product URL": product_url
    })
 
df = pd.DataFrame(products)
df

# 9. Archivos de imagen

Una imagen digital puede interpretarse como una matriz de píxeles. En una imagen RGB, la forma suele ser `(alto, ancho, 3)`: el último eje contiene los canales rojo, verde y azul. En imágenes con transparencia puede aparecer un cuarto canal alfa.

Leer una imagen como arreglo permite crear características numéricas, por ejemplo promedios de color, histogramas, bordes o texturas. Antes de modelar conviene revisar el rango de valores, el tipo de dato, la orientación y si todas las imágenes tienen la misma resolución.

Las imágenes RGB almacenan información de color en tres canales: Rojo (R), Verde (G) y Azul (B). Para leer y manipular imágenes en Python, se pueden usar las librerías `Pillow` (PIL), `matplotlib` y `numpy`. Esto permite acceder a los valores de los píxeles y realizar análisis o transformaciones.

En las celdas siguientes se observa la imagen completa, un canal individual y una versión en escala de grises. La conversión mediante el promedio es didáctica; para aplicaciones sensibles a la percepción humana suele ser preferible una transformación ponderada como la de luminancia.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
I=plt.imread(ruta+'imagen.bmp')
I.shape

In [ ]:
type(I)

In [ ]:
plt.imshow(I)

In [ ]:
I[0,0,0] # pixel (0,0) de la matriz roja

In [ ]:
plt.imshow(I[:,:,0],cmap='gray') # Matriz roja

In [ ]:
G=I.mean(axis=2)
G.shape

In [ ]:
plt.imshow(G)

In [ ]:
G[0,0]

# 10. Aplicaciones en Ciencias de Datos

La fuente determina qué información puede conservarse y qué transformaciones serán necesarias. La siguiente guía conecta cada formato con tareas frecuentes de análisis y ayuda a elegir una primera estrategia de extracción.

```mermaid
flowchart TD
    Q{¿Cómo está organizada la fuente?}
    Q -->|Filas y columnas| T[CSV o Excel]
    Q -->|Texto libre| X[Texto y regex]
    Q -->|Objetos anidados| J[JSON o XML]
    Q -->|Geometría y atributos| S[Shapefile]
    Q -->|Etiquetas de una página| H[HTML]
    Q -->|Píxeles| I[Imagen]
    T --> R[DataFrame]
    X --> R
    J --> R
    S --> R
    H --> R
    I --> M[Matriz o características]
```

## Archivos de texto

Son adecuados cuando la señal principal está en el lenguaje. Después de extraer el contenido, una canalización típica incluye normalización, tokenización, eliminación o conservación consciente de palabras vacías y generación de características. Las regex funcionan bien para patrones concretos, pero no sustituyen un análisis lingüístico completo.

> **Aplicaciones:** análisis de sentimientos, extracción de palabras clave, procesamiento de lenguaje natural y análisis de logs para detectar patrones o anomalías.

### Archivos Excel y CSV

Son una buena entrada para análisis exploratorio y preparación de datos porque ya expresan observaciones en filas y variables en columnas. La extracción debe ir acompañada de validaciones de tipos, duplicados, valores faltantes y unidades.

> **Aplicaciones:** agrupar ventas por producto, preparar características para modelos de machine learning y generar reportes mensuales de ingresos.

### Archivos de imágenes RGB

La imagen se convierte en variables numéricas antes de entrenar un modelo. Además de los canales de color, pueden extraerse histogramas, bordes, texturas o representaciones aprendidas por redes convolucionales.

> **Aplicaciones:** clasificar dígitos escritos a mano, detectar regiones anómalas en imágenes médicas y calcular histogramas de color.

### Archivos XML

> **Integración de datos de sistemas empresariales:**
  - Extraer información de clientes de un archivo XML exportado de un ERP.
    
> **Procesamiento de datos de sensores o dispositivos IoT:**
  - Leer registros de temperatura almacenados en XML.
    
> **Análisis de datos de publicaciones científicas:**
  - Obtener títulos y autores de artículos en formato XML

### Archivos JSON

> **Consumo de APIs web:**
  - Obtener y analizar tweets desde la API de Twitter.
    
> **Almacenamiento y análisis de logs:**
  - Procesar registros de acceso de una aplicación web.
    
> **Análisis de datos de aplicaciones móviles:**
  - Leer resultados de encuestas exportadas en JSON.

### Archivos Shapefile (SHP)

> **Análisis geoespacial:**
  - Calcular la distancia entre puntos de interés en una ciudad.
    
> **Estudios ambientales y urbanos:**
  - Analizar la distribución de áreas verdes en una zona urbana.

> **Modelado de redes y transporte:**
  - Determinar rutas óptimas entre dos ubicaciones.

## Archivos HTML:
> **Web scraping:** Extraer datos estructurados de páginas web para análisis posterior.

> **Construcción de datasets:** Recolectar información de múltiples páginas HTML para crear conjuntos de datos.

> **Análisis de enlaces:** Estudiar la estructura de enlaces en sitios web para análisis de redes.

> **Extracción de tablas:** Obtener datos tabulares de páginas HTML para análisis estadístico.